version: '3.3'
services:
  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'qwerty'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: